import { logger } from "../utils/logger.js";
import { getSupabase } from "../rag/supabase.js";
import { v4 as uuidv4 } from "uuid";
import fetch from "node-fetch";

/**
 * Generates an MP3 audio buffer from text using Cartesia API and uploads it to Supabase Storage.
 * @param text The conversational reply generated by the AI
 * @returns The public URL of the MP3 file hosted on Supabase Storage
 */
export async function generateAndUploadAudio(text: string): Promise<string> {
  const apiKey = process.env.CARTESIA_API_KEY;
  if (!apiKey) throw new Error("CARTESIA_API_KEY is not set");

  logger.info(`Generating audio via Cartesia for text: ${text.substring(0, 50)}...`);
  
  try {
    const response = await fetch("https://api.cartesia.ai/tts/bytes", {
      method: "POST",
      headers: {
        "Cartesia-Version": "2024-06-10",
        "X-API-Key": apiKey,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        transcript: text,
        model_id: "sonic-english",
        voice: {
          mode: "id",
          id: "cec7cae1-ac8b-4a59-9eac-ec48366f37ae" // Fetched valid voice ID
        },
        output_format: {
          container: "mp3",
          encoding: "mp3",
          sample_rate: 44100
        }
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      logger.error("Cartesia API error:", errText);
      throw new Error(`Failed to generate TTS audio: ${response.status} ${errText}`);
    }

    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Upload to Supabase public bucket
    const supabase = getSupabase();
    const fileName = `twilio_audio/${uuidv4()}.mp3`;

    const { error } = await supabase
      .storage
      .from("documents") // the public documents bucket used across this app
      .upload(fileName, buffer, {
        contentType: "audio/mpeg",
        cacheControl: "3600",
        upsert: false
      });

    if (error) {
      logger.error("Supabase Storage upload error:", error);
      throw new Error("Failed to upload audio to Supabase Storage");
    }

    // Get the public URL for the newly uploaded audio file
    const { data: publicData } = supabase.storage.from("documents").getPublicUrl(fileName);
    logger.info(`Successfully generated and uploaded audio: ${publicData.publicUrl}`);
    
    return publicData.publicUrl;
  } catch (error) {
    logger.error("Error in generateAndUploadAudio:", error);
    throw error;
  }
}
